sudo: required

language: go

services:
  - docker

script:
# Run unit tests
  - go test ./encoding
  - go test ./tsm
  - go test ./types
  - go test ./utsm
# Make sure everything can build
  - go build -o ./baccli/bacccli ./baccli
# Run Test that require a test server
  - docker pull ucmercedandeslab/bacnet-server
  - docker run -it --rm -d ucmercedandeslab/bacnet-server
  - go test -c 
  - docker run -it --rm -v $(pwd):/opt/ debian /opt/gobacnet.test -test.v